export const FEATURE_TYPES = [
  "window",
  "door",
  "garage",
  "balcony",
  "patio",
  "pool",
  "driveway",
  "room",
  "building",
  "road",
  "parking",
  "landscape",
  "deck",
  "porch",
  "chimney",
  "curvedWall",
  "arch",
  "bay",
  "foundation",
  "stairs",
  "dormer",
  "crossGable",
  "retainingWall",
  "path",
  "waterway",
  "rockCluster",
  "slope",
] as const;

export type FeatureType = (typeof FEATURE_TYPES)[number];

/** Single source of truth mapping a feature type to its plural JSON array key. */
export const FEATURE_JSON_KEY: Record<FeatureType, string> = {
  window: "windows",
  door: "doors",
  garage: "garages",
  balcony: "balconies",
  patio: "patios",
  pool: "pools",
  driveway: "driveways",
  room: "rooms",
  building: "buildings",
  road: "roads",
  parking: "parking",
  landscape: "landscaping",
  deck: "decks",
  porch: "porches",
  chimney: "chimneys",
  curvedWall: "curvedWalls",
  arch: "arches",
  bay: "bays",
  foundation: "foundations",
  stairs: "stairs",
  dormer: "dormers",
  crossGable: "crossGables",
  retainingWall: "retainingWalls",
  path: "paths",
  waterway: "waterways",
  rockCluster: "rocks",
  slope: "slopes",
};

export const FEATURE_LABEL: Record<FeatureType, string> = {
  window: "Window",
  door: "Door",
  garage: "Garage",
  balcony: "Balcony",
  patio: "Patio",
  pool: "Pool",
  driveway: "Driveway",
  room: "Room",
  building: "Building",
  road: "Road",
  parking: "Parking Lot",
  landscape: "Landscaping",
  deck: "Deck",
  porch: "Porch",
  chimney: "Chimney",
  curvedWall: "Curved Wall",
  arch: "Arch",
  bay: "Bay / Turret",
  foundation: "Foundation",
  stairs: "Stairs",
  dormer: "Dormer",
  crossGable: "Cross Gable",
  retainingWall: "Retaining Wall",
  path: "Path",
  waterway: "River / Stream",
  rockCluster: "Rocks",
  slope: "Slope",
};
