import type { AssetRequest, CapabilityRequest, DesignRecipe } from "@/types/library";
import type { CompassSide, ProjectScale, RoofType, SiteEnvironment } from "@/types/house";

export type IntentGoal = "privacy" | "openness" | "views" | "shelter" | "cross-ventilation" | "daylight" | "indoor-outdoor" | "resort-feeling" | "formality" | "informality" | "symmetry" | "asymmetry" | "horizontal-emphasis" | "vertical-emphasis" | "calm" | "drama" | "intimacy" | "grand-entertaining" | "family-living" | "guest-private-service-separation";
export type SpaceZone = "arrival" | "public-living" | "dining" | "kitchen" | "private-bedrooms" | "master-suite" | "guest" | "service" | "garage" | "outdoor-living" | "pool" | "garden-courtyard";
export type StrategyName = "Pavilion Composition" | "Courtyard Composition" | "Stepped Hillside" | "Offset Wings" | "Framed View Axis" | "Arrival Court" | "Deep Overhang" | "Private Bedroom Wing" | "Detached Guest Pavilion" | "Linear View Bar";

/** Goals only; never geometry. This is the durable answer to why a house takes its form. */
export interface ArchitecturalIntent { mood: IntentGoal[]; spatialGoals: IntentGoal[]; environmentalGoals: IntentGoal[]; hierarchyGoals: string[]; compositionBias: "symmetrical" | "asymmetrical" | "linear" | "stepped"; source: { environment: SiteEnvironment; scale: ProjectScale | undefined; viewDirection: CompassSide; arrivalDirection: CompassSide; style: string }; }
export interface DesignStrategy { name: StrategyName; satisfies: IntentGoal[]; requiredCapabilities: string[]; preferredRecipeCategories: string[]; spatialConsequences: string[]; }
export interface SpaceRelationship { from: SpaceZone; to: SpaceZone; relationship: "adjacent" | "buffered" | "separated" | "faces-view" | "outdoor-connected" | "arrival-facing" | "private"; reason: string; }
export interface SpacePlan { zones: { zone: SpaceZone; priority: "primary" | "secondary" | "support"; viewFacing: boolean; private: boolean; outdoorConnected: boolean }[]; relationships: SpaceRelationship[]; circulation: { arrival: string; publicToPrivate: string; service: string }; massAssignments: { id: string; role: "main-living" | "private-wing" | "guest-wing" | "service" | "pavilion"; zones: SpaceZone[] }[]; }

export interface ArchitecturalDesign {
  version: 1;
  pipeline: readonly ["brief", "architectural-intent", "design-strategy", "space-planning", "massing", "space-relationships", "roof-composition", "facade-language", "components", "outdoor-spaces", "landscape", "retrieve-library", "generate-recipes", "generate-assets", "assemble", "learn"];
  intent: ArchitecturalIntent; strategies: DesignStrategy[]; spacePlan: SpacePlan;
  concept: { name: string; philosophy: string; buildingHierarchy: string[]; visualRhythm: string; roofStrategy: string; materialPalette: string[]; circulation: string; zoning: string; indoorOutdoor: string; viewStrategy: string; arrivalSequence: string };
  siteAnalysis: { environment: SiteEnvironment; viewDirection: CompassSide; approachSide: CompassSide; terrainResponse: string };
  masses: { id: string; role: "main-living" | "private-wing" | "guest-wing" | "service" | "pavilion"; relationship: string; roof: RoofType }[];
  spaceRelationships: { from: string; to: string; relationship: "direct" | "buffered" | "framed" | "separate" }[];
  roofComposition: { family: string; primary: RoofType; secondary: RoofType; pitch: number; overhang: number; details: string[] };
  facadeLanguage: { base: string; openings: string; shading: string; rhythm: string }; components: { name: string; required: boolean; dimensions?: { width?: number; height?: number; depth?: number } }[]; outdoorStrategy: string[]; landscapeStrategy: string[];
}
const has = (text: string, re: RegExp) => re.test(text);
const viewSide = (text: string, fallback: CompassSide): CompassSide => has(text, /sunrise|east/i) ? "east" : has(text, /sunset|west/i) ? "west" : fallback;
const hash = (s: string) => [...s].reduce((n, c) => (n * 31 + c.charCodeAt(0)) >>> 0, 7);
const makeStrategy = (name: StrategyName, satisfies: IntentGoal[], requiredCapabilities: string[], spatialConsequences: string[], preferredRecipeCategories: string[] = []): DesignStrategy => ({ name, satisfies, requiredCapabilities, spatialConsequences, preferredRecipeCategories });

export function deriveArchitecturalIntent(brief: string, input: { environment: SiteEnvironment; viewDirection: CompassSide; approachSide: CompassSide; scale?: ProjectScale }): ArchitecturalIntent {
  const b = brief.toLowerCase(), tropical = has(b, /tropical|caribbean|island|beach|balinese|resort/), hillside = input.environment === "hillside" || input.environment === "cliff" || has(b, /hillside|cliff|slope/), privateBrief = has(b, /private|secluded|sanctuary/), entertaining = has(b, /entertain|gather|host|party|family/), views = has(b, /view|ocean|waterfront|lake|sunset|sunrise/);
  return { mood: [has(b, /dramatic|bold/) ? "drama" : "calm", ...(tropical ? ["resort-feeling" as const] : []), ...(entertaining ? ["informality" as const] : [])], spatialGoals: [privateBrief ? "privacy" : "openness", ...(privateBrief ? ["intimacy" as const] : []), ...(views ? ["views" as const] : []), ...(tropical || entertaining ? ["indoor-outdoor" as const] : []), entertaining ? "grand-entertaining" : "family-living", "guest-private-service-separation"], environmentalGoals: [tropical ? "cross-ventilation" : "daylight", ...(tropical || hillside ? ["shelter" as const] : [])], hierarchyGoals: [entertaining ? "dominant living pavilion" : "legible main living volume", privateBrief ? "protected private bedroom wing" : "quiet private wing", "service kept out of the view sequence"], compositionBias: hillside ? "stepped" : has(b, /symmetr/) ? "symmetrical" : views ? "linear" : "asymmetrical", source: { environment: input.environment, scale: input.scale, viewDirection: viewSide(brief, input.viewDirection), arrivalDirection: input.approachSide, style: tropical ? "modern tropical" : has(b, /contemporary/) ? "contemporary" : "modern" } };
}

/** Stable seed controls plausible alternatives without introducing random chaos. */
export function selectDesignStrategies(intent: ArchitecturalIntent, recipes: readonly DesignRecipe[] = [], availableCapabilities: readonly string[] = [], variationSeed = ""): DesignStrategy[] {
  const supported = (id: string) => !availableCapabilities.length || availableCapabilities.includes(id); const categories = recipes.filter((r) => r.approval === "approved").map((r) => r.category).join("/"); const pick = <T,>(xs: T[]) => xs[hash(`${variationSeed}|${intent.compositionBias}|${categories}`) % xs.length];
  const result = [makeStrategy("Framed View Axis", ["views"], ["corner-glazing"], ["living, outdoor living and master address the view"], ["terrace"]), makeStrategy("Private Bedroom Wing", ["privacy", "guest-private-service-separation"], ["split-mass"], ["private rooms buffer from public living"])];
  if (intent.compositionBias === "stepped") result.push(makeStrategy("Stepped Hillside", ["views", "shelter"], ["step-mass"], ["masses step with terrain and preserve terraces"]));
  else if (intent.spatialGoals.includes("privacy") && pick([true, false])) result.push(makeStrategy("Courtyard Composition", ["privacy", "indoor-outdoor"], ["courtyard-composition"], ["wings protect a central outdoor room"], ["courtyard"]));
  else if (intent.compositionBias === "linear") result.push(makeStrategy("Linear View Bar", ["views", "horizontal-emphasis"], ["split-mass"], ["public rooms form a view-facing bar"]));
  else result.push(pick([makeStrategy("Pavilion Composition", ["indoor-outdoor", "resort-feeling"], ["split-mass"], ["separate pavilions establish hierarchy"]), makeStrategy("Offset Wings", ["asymmetry", "privacy"], ["offset-mass"], ["wings stagger into shaded outdoor pockets"])]));
  if (intent.spatialGoals.includes("grand-entertaining")) result.push(makeStrategy("Arrival Court", ["formality", "drama"], ["recessed-entry"], ["arrival pauses before the public heart"], ["entry-sequence"]));
  if (intent.environmentalGoals.includes("shelter")) result.push(makeStrategy("Deep Overhang", ["shelter", "indoor-outdoor"], ["deep-overhang"], ["outdoor living stays protected"]));
  return result.filter((s) => s.requiredCapabilities.every(supported));
}

export function createSpacePlan(intent: ArchitecturalIntent, strategies: readonly DesignStrategy[]): SpacePlan {
  const courtyard = strategies.some((s) => s.name === "Courtyard Composition"), guest = intent.source.scale === "estate" || intent.source.scale === "mansion";
  const zones: SpacePlan["zones"] = [{ zone: "arrival", priority: "secondary", viewFacing: false, private: false, outdoorConnected: true }, { zone: "public-living", priority: "primary", viewFacing: true, private: false, outdoorConnected: true }, { zone: "dining", priority: "primary", viewFacing: true, private: false, outdoorConnected: true }, { zone: "kitchen", priority: "secondary", viewFacing: false, private: false, outdoorConnected: false }, { zone: "private-bedrooms", priority: "secondary", viewFacing: false, private: true, outdoorConnected: false }, { zone: "master-suite", priority: "primary", viewFacing: true, private: true, outdoorConnected: true }, { zone: "service", priority: "support", viewFacing: false, private: true, outdoorConnected: false }, { zone: "garage", priority: "support", viewFacing: false, private: false, outdoorConnected: false }, { zone: "outdoor-living", priority: "primary", viewFacing: true, private: false, outdoorConnected: true }, { zone: "pool", priority: "secondary", viewFacing: true, private: false, outdoorConnected: true }, { zone: "garden-courtyard", priority: "secondary", viewFacing: courtyard, private: courtyard, outdoorConnected: true }, ...(guest ? [{ zone: "guest" as const, priority: "secondary" as const, viewFacing: true, private: true, outdoorConnected: true }] : [])];
  const relationships: SpaceRelationship[] = [{ from: "arrival", to: "public-living", relationship: "arrival-facing", reason: "arrival releases through the public heart" }, { from: "public-living", to: "dining", relationship: "adjacent", reason: "daily gathering remains continuous" }, { from: "public-living", to: "outdoor-living", relationship: "outdoor-connected", reason: "living expands to climate and view" }, { from: "public-living", to: "master-suite", relationship: "separated", reason: "private retreat stays quiet" }, { from: "master-suite", to: "outdoor-living", relationship: "faces-view", reason: "private terrace shares the outlook" }, { from: "kitchen", to: "service", relationship: "adjacent", reason: "service circulation stays discreet" }, { from: "garage", to: "arrival", relationship: "arrival-facing", reason: "vehicles stay on the approach side" }, { from: "garage", to: "pool", relationship: "separated", reason: "pool remains private from arrival" }];
  const massAssignments: SpacePlan["massAssignments"] = [{ id: "living-pavilion", role: "main-living", zones: ["public-living", "dining", "kitchen"] }, { id: "private-wing", role: "private-wing", zones: ["private-bedrooms", "master-suite"] }, { id: "outdoor-pavilion", role: "pavilion", zones: ["outdoor-living", "pool", "garden-courtyard"] }, { id: "service-spine", role: "service", zones: ["service", "garage", "arrival"] }]; if (guest) massAssignments.push({ id: "guest-pavilion", role: "guest-wing", zones: ["guest"] });
  return { zones, relationships, circulation: { arrival: "arrival court → sheltered entry → living view reveal", publicToPrivate: "living pavilion → buffered private wing", service: "garage → service spine → kitchen, separate from guests" }, massAssignments };
}

export function designArchitecture(brief: string, input: { environment: SiteEnvironment; viewDirection: CompassSide; approachSide: CompassSide; scale?: ProjectScale; recipes?: readonly DesignRecipe[]; availableCapabilities?: readonly string[]; variationSeed?: string }): ArchitecturalDesign {
  const b = brief.toLowerCase(), intent = deriveArchitecturalIntent(brief, input), strategies = selectDesignStrategies(intent, input.recipes, input.availableCapabilities, input.variationSeed), spacePlan = createSpacePlan(intent, strategies), tropical = /tropical|caribbean|island|beach|balinese|resort/.test(b), hillside = strategies.some((s) => s.name === "Stepped Hillside"), courtyard = strategies.some((s) => s.name === "Courtyard Composition"), caribbean = /caribbean/.test(b), balinese = /balinese/.test(b), name = balinese ? "Balinese Resort" : courtyard ? "Luxury Courtyard Residence" : hillside ? "Contemporary Hillside Residence" : caribbean ? "Minimal Caribbean Villa" : tropical ? "Modern Tropical Estate" : intent.compositionBias === "linear" ? "Contemporary View Bar Residence" : "Contemporary Pavilion Residence", primary: RoofType = balinese || caribbean ? "hip" : hillside ? "shed" : tropical ? "butterfly" : "flat", secondary: RoofType = primary === "flat" ? "shed" : "flat", palette = balinese ? ["natural teak", "basalt", "warm limestone", "standing seam metal"] : caribbean ? ["white coral render", "natural teak", "black aluminum", "slate"] : tropical ? ["board formed concrete", "travertine", "natural teak", "black aluminum"] : ["charcoal stucco", "limestone", "black aluminum", "corten steel"];
  const masses = spacePlan.massAssignments.map((a) => ({ id: a.id, role: a.role, relationship: `${a.zones.join(", ")}${courtyard && a.id !== "service-spine" ? " frame a protected courtyard" : a.id === "private-wing" ? " buffer from public living" : " support planned circulation"}`, roof: a.role === "main-living" ? primary : a.role === "private-wing" ? secondary : "flat" as RoofType }));
  const components = [{ name: "6m Sliding Glass Door", required: true, dimensions: { width: 6, height: 2.8 } }, { name: "Timber Louver Screen", required: tropical || courtyard, dimensions: { width: 2.4, height: 3 } }, { name: "Modern Tropical Fascia", required: tropical, dimensions: { depth: 0.35 } }, { name: "Pergola Beam System", required: tropical || courtyard, dimensions: { width: 4, depth: 3, height: 2.8 } }].filter((c) => c.required || c.name === "6m Sliding Glass Door");
  return { version: 1, pipeline: ["brief", "architectural-intent", "design-strategy", "space-planning", "massing", "space-relationships", "roof-composition", "facade-language", "components", "outdoor-spaces", "landscape", "retrieve-library", "generate-recipes", "generate-assets", "assemble", "learn"], intent, strategies, spacePlan, concept: { name, philosophy: "Intent-led composition: goals and relationships determine masses before facade expression.", buildingHierarchy: intent.hierarchyGoals, visualRhythm: "Alternating solid, glazing and shaded screen bays.", roofStrategy: primary === "flat" ? "Layered flat plates with a secondary shed wing." : "Primary pitched pavilion roof with lower related roofs.", materialPalette: palette, circulation: spacePlan.circulation.arrival, zoning: "Public living faces the view; private and service zones remain buffered.", indoorOutdoor: "Deep thresholds and operable glazing make exterior rooms part of daily life.", viewStrategy: `Frame the ${intent.source.viewDirection} view from living, master and outdoor living.`, arrivalSequence: spacePlan.circulation.arrival }, siteAnalysis: { environment: input.environment, viewDirection: intent.source.viewDirection, approachSide: input.approachSide, terrainResponse: hillside ? "Step masses with the land and terrace the view side." : "Keep the arrival edge composed and reserve the view side for outdoor living." }, masses, spaceRelationships: spacePlan.relationships.map((r) => ({ from: r.from, to: r.to, relationship: r.relationship === "adjacent" || r.relationship === "outdoor-connected" ? "direct" : r.relationship === "faces-view" || r.relationship === "arrival-facing" ? "framed" : r.relationship === "separated" ? "separate" : "buffered" })), roofComposition: { family: primary === "hip" ? "Modern Caribbean / resort hip" : primary === "butterfly" ? "Modern tropical butterfly" : primary === "shed" ? "Hillside shed composition" : "Layered flat roof composition", primary, secondary, pitch: primary === "flat" ? 2 : primary === "hip" ? 28 : 14, overhang: intent.environmentalGoals.includes("shelter") ? 1.4 : 0.75, details: ["continuous fascia", "deep soffits", "integrated gutters", "ridge caps where pitched"] }, facadeLanguage: { base: palette[0], openings: "Large view-side sliding panels and protected corner glazing.", shading: tropical ? "Timber louvers and deep eaves." : "Recessed openings and slender overhangs.", rhythm: "A deliberate cadence of opaque piers, glazing and screens." }, components, outdoorStrategy: ["Outdoor living aligns with the view-side living pavilion", "Pool and terrace remain private from arrival"], landscapeStrategy: ["Plant a layered arrival threshold", "Frame rather than block primary views"] };
}
export function architecturalCapabilityRequests(design: ArchitecturalDesign): CapabilityRequest[] { return [...new Set(design.strategies.flatMap((s) => s.requiredCapabilities))].map((operation) => ({ operation, stage: "design-strategy", desiredBehaviour: design.strategies.filter((s) => s.requiredCapabilities.includes(operation)).map((s) => s.spatialConsequences.join("; ")).join("; ") })); }
export function architecturalAssetRequests(design: ArchitecturalDesign, projectId: string | null): AssetRequest[] { return design.components.map((component) => ({ text: component.name, category: "architectural-component", styleTags: design.intent.source.style.split(/\s+/), contextTags: ["facade"], dimensions: component.dimensions, projectId })); }
